apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "725211be-2cae-4adb-9497-07fccdc6e080"
    keyvaultName: challenge4Keyvault
    cloudName: AzurePublicCloud
    objects: >
      array:
        - |
          objectName: sqluser
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
          objectAlias: "SQL_USER"		  
        - |
          objectName: sqlpassword
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
          objectAlias: "SQL_PASSWORD"
        - |
          objectName: sqlserver
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
          objectAlias: "SQL_SERVER"		  
    tenantId: 88443654-3c6a-41a1-90f1-632b138878e4